image: python:3.7-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - cd doc
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - master
  - 30-documentation
