image: python:3.7-alpine

stages:
  - test
  - deploy

pylint:
  stage: test
  script:
  - pip install pylint
  - ./pylint-monitor
  

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - cd doc
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - master

