image: python:3.8-slim

stages:
  - build
  - test
  - deploy

pylint:
  stage: test
  script:
  - python3 -c 'import sys; f = open("/usr/local/lib/python3.8/site-packages/_manylinux.py", "w"); f.write("manylinux1_compatible = True"); f.close()'
  - pip install --upgrade astroid
  - pip install pylint
  - python pylint-monitor

doctest:
  stage: test
  script:
  - apt-get -y gcc g++ libfftw3-dev libgsl-dev 
  - pip install -r requirements.txt
  - python ldc/waveform/waveform/hphc.py

pages:
  stage: deploy
  script:
  - apt-get -y gcc g++ 
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - cd doc
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - master

