image: python:3.8-slim

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - deploy

pylint:
  stage: test
  script:
  - python3 -c 'import sys; f = open("/usr/local/lib/python3.8/site-packages/_manylinux.py", "w"); f.write("manylinux1_compatible = True"); f.close()'
  - pip install --upgrade astroid
  - pip install pylint
  - python pylint-monitor

doctest:
  stage: test
  script:
  - apt-get update
  - apt-get -y install gcc g++ libfftw3-dev libgsl-dev 
  - pip install -r requirements.txt
  - python ldc/waveform/waveform/hphc.py

docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - apk add --no-cache git
    - git clone --single-branch --branch ldc-pipeline https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.in2p3.fr/j2b.bayle/LISANode.git
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  only:
  - master

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get -y install gcc g++ 
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - cd doc
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - master

