image: python:3.7-alpine

stages:
  - build
  - test
  - deploy

pylint:
  stage: test
  script:
  - python3 -c 'import sys; f = open("/usr/local/lib/python3.7/site-packages/_manylinux.py", "w"); f.write("manylinux1_compatible = True"); f.close()'
  - pip install --upgrade astroid
  - pip install pylint
  - python pylint-monitor

doctest:
  image: debian:buster-slim
  stage: test
  script:
  - apt-get -y update && apt-get -y --no-install-recommends install \
      python3=3.7.3-1 \
      python3-pip=18.1-5 \
      gcc=4:8.3.0-1 \
      g++=4:8.3.0-1 \
      make=4.2.1-1.2 \
      python3.7-dev=3.7.3-2+deb10u1 \
      libfftw3-dev=3.3.8-2 \
      libgsl-dev=2.5+dfsg-6 && rm -rf /var/lib/apt/lists/* \
  - pip install -r requirements.txt
  - python ldc/waveform/waveform/hphc.py

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - cd doc
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - master

