site_name: LDC pipeline
site_url: https://maudelejeune.pages.in2p3.fr/LDCPipeline/
use_directory_urls: false
site_favicon: favicon.ico
pages:
- Home: 'index.md'  
- User guide:
  - Installation: 'installation.md'
  - Running: 'running.md'
  - Running at CCIN2P3: 'running_cc.md'
  - Running at CNES: 'running_hal.md'
  - Pipeline products: 'products.md'
  - Performance: 'perf.md'
- Project:
  - Status: 'status.md'
  - References: 'reference.md'

- Getting help:
  - Tutorials: 'tuto.md'
  - FAQ: 'faq.md'



#theme:
#    name: null
#    custom_dir: 'cinder'

markdown_extensions:
  - admonition
